package org.elsys.motorcycle_security.business.logic;

import org.elsys.motorcycle_security.models.Devices;
import org.elsys.motorcycle_security.repository.DevicesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class DevicesHandler {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DevicesRepository DevicesRepository;

    public void UpdateDevices(Long userid){
        Devices d = new Devices();
        d.setUserid(userid);
        DevicesRepository.save(d);
    }
}
