package org.elsys.motorcycle_security.business.logic;

import org.elsys.motorcycle_security.models.DeviceStatus;
import org.elsys.motorcycle_security.repository.DeviceStatusRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class DeviceStatusHandler {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DeviceStatusRepository DeviceStatusRepository;

    public void UpdateDeviceStaus(boolean isParked, long x, long y, long timeout , long deviceid){
        DeviceStatus d = new DeviceStatus();
        d.setParked(isParked);
        d.setX(x);
        d.setY(y);
        d.setTimeout(timeout);
        d.setDeviceid(deviceid);
        DeviceStatusRepository.save(d);
    }
}
