package org.elsys.motorcycle_security.business.logic;

import org.elsys.motorcycle_security.SendGPSCords;
import org.elsys.motorcycle_security.models.DataTransmiter;
import org.elsys.motorcycle_security.repository.DataTransmiterRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.text.SimpleDateFormat;


@Component
public class GPSCordsHandler {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DataTransmiterRepository dataTransmiterRepository;

    public SendGPSCords getLatestCordsForUser(int id){
        return new SendGPSCords(1,1);
    }

    public void UpdateGPSCords(Long deviceid,Long x,Long y){
        DataTransmiter d = new DataTransmiter();
        d.setDeviceid(deviceid);
        d.setX(x);
        d.setY(y);
        Long Date = System.currentTimeMillis();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
        String CurrDay = sdf.format(Date);
        d.setTime(CurrDay);
        dataTransmiterRepository.save(d);
    }
    public void GetGPSCords(Long deviceid){
        DataTransmiter d = new DataTransmiter();
    }
}
